const PRODUCTS = [
  {
    "id": 9221207785731,
    "title": "Azure Fringe Mini Dress",
    "slug": "azure-fringe-mini-dress",
    "price": 25500.0,
    "priceFormatted": "25 500 ₽",
    "image": "images/products/9221207785731.jpg",
    "handle": "azure-fringe-mini-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Лазурное мини-платье с бахромой",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221307105539,
    "title": "Beige Sparkle Maxi Dress",
    "slug": "beige-sparkle-maxi-dress",
    "price": 29000.0,
    "priceFormatted": "29 000 ₽",
    "image": "images/products/9221307105539.jpg",
    "handle": "beige-sparkle-maxi-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "maxi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Бежевое макси-платье с кристаллами",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "light",
    "colorRu": "Светлый"
  },
  {
    "id": 9221335351555,
    "title": "Beige Sparkle Midi Dress",
    "slug": "beige-sparkle-midi-dress",
    "price": 23500.0,
    "priceFormatted": "23 500 ₽",
    "image": "images/products/9221335351555.jpg",
    "handle": "beige-sparkle-midi-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "midi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Бежевое миди-платье с кристаллами",
    "category": "midi",
    "categoryRu": "Миди",
    "color": "light",
    "colorRu": "Светлый"
  },
  {
    "id": 9221324308739,
    "title": "Black  Sparkle Mid i Dress",
    "slug": "black-sparkle-mid-i-dress",
    "price": 23500.0,
    "priceFormatted": "23 500 ₽",
    "image": "images/products/9221324308739.jpg",
    "handle": "black-sparkle-mid-i-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "midi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное миди-платье с кристаллами",
    "category": "midi",
    "categoryRu": "Миди",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9221028675843,
    "title": "Black Baccarat Silk Dress",
    "slug": "black-baccarat-silk-dress",
    "price": 37500.0,
    "priceFormatted": "37 500 ₽",
    "image": "images/products/9221028675843.jpg",
    "handle": "black-baccarat-silk-dress",
    "description": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "maxi dress",
      "romantic"
    ],
    "available": true,
    "descriptionRu": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное платье шёлковое Baccarat",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9221125898499,
    "title": "Black Flounce Mini Dress",
    "slug": "black-flounce-mini-dress",
    "price": 22800.0,
    "priceFormatted": "22 800 ₽",
    "image": "images/products/9221125898499.jpg",
    "handle": "black-flounce-mini-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное мини-платье с воланами",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9221180031235,
    "title": "Black Gatsby Midi Dress",
    "slug": "black-gatsby-midi-dress",
    "price": 27800.0,
    "priceFormatted": "27 800 ₽",
    "image": "images/products/9221180031235.jpg",
    "handle": "black-gatsby-midi-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "midi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное миди-платье Gatsby",
    "category": "midi",
    "categoryRu": "Миди",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9220907761923,
    "title": "Black Jasmine Midi Dress",
    "slug": "black-jasmine-midi-dress",
    "price": 28500.0,
    "priceFormatted": "28 500 ₽",
    "image": "images/products/9220907761923.jpg",
    "handle": "black-jasmine-midi-dress",
    "description": "Элегантное миди-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "floral",
      "midi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное миди-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное миди-платье Jasmine",
    "category": "midi",
    "categoryRu": "Миди",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9221084545283,
    "title": "Black Lace Mini Dress",
    "slug": "black-lace-mini-dress",
    "price": 25500.0,
    "priceFormatted": "25 500 ₽",
    "image": "images/products/9221084545283.jpg",
    "handle": "black-lace-dress",
    "description": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "lace",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное мини-платье кружевное",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9221613256963,
    "title": "Black Noir Maxi Dress",
    "slug": "black-noir-maxi-dress",
    "price": 64990.0,
    "priceFormatted": "64 990 ₽",
    "image": "images/products/9221613256963.jpg",
    "handle": "black-noir-maxi-dress",
    "description": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "evening dress",
      "feminine",
      "maxi dress",
      "midi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное макси-платье Noir",
    "category": "midi",
    "categoryRu": "Миди",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9220437115139,
    "title": "Black Orchid Midi Dress",
    "slug": "black-orchid-midi-dress",
    "price": 27500.0,
    "priceFormatted": "27 500 ₽",
    "image": "images/products/9220437115139.jpg",
    "handle": "black-orchid-midi-dress",
    "description": "Элегантное миди-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "floral",
      "lace",
      "midi dress",
      "romantic"
    ],
    "available": true,
    "descriptionRu": "Элегантное миди-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное миди-платье Orchid",
    "category": "midi",
    "categoryRu": "Миди",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9220852547843,
    "title": "Black Peony Midi Dress",
    "slug": "black-peony-midi-dress",
    "price": 27500.0,
    "priceFormatted": "27 500 ₽",
    "image": "images/products/9220852547843.jpg",
    "handle": "black-peony-midi-dress",
    "description": "Элегантное миди-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "floral",
      "midi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное миди-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное миди-платье Peony",
    "category": "midi",
    "categoryRu": "Миди",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9221293834499,
    "title": "Black Sparkle Maxi Dress",
    "slug": "black-sparkle-maxi-dress",
    "price": 29000.0,
    "priceFormatted": "29 000 ₽",
    "image": "images/products/9221293834499.jpg",
    "handle": "black-sparkle-maxi-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "maxi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное макси-платье с кристаллами",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9221602509059,
    "title": "Black Tweed Mini Dress",
    "slug": "black-tweed-mini-dress",
    "price": 32500.0,
    "priceFormatted": "32 500 ₽",
    "image": "images/products/9221602509059.jpg",
    "handle": "black-tweed-mini-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное мини-платье твидовое",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9221141659907,
    "title": "Black Velour Rose Mini Dress",
    "slug": "black-velour-rose-mini-dress",
    "price": 27200.0,
    "priceFormatted": "27 200 ₽",
    "image": "images/products/9221141659907.jpg",
    "handle": "black-velour-rose-mini-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное мини-платье бархатная роза",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9220938760451,
    "title": "Blossom Corset Maxi Dress",
    "slug": "blossom-corset-maxi-dress",
    "price": 39800.0,
    "priceFormatted": "39 800 ₽",
    "image": "images/products/9220938760451.jpg",
    "handle": "blossom-corset-maxi-dress",
    "description": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "floral",
      "lace",
      "m",
      "maxi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Цветочное макси-платье корсетное",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9220399366403,
    "title": "Bluebell Mini Dress",
    "slug": "bluebell-mini-dress",
    "price": 23500.0,
    "priceFormatted": "23 500 ₽",
    "image": "images/products/9220399366403.jpg",
    "handle": "bluebell-mini-dress",
    "description": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "floral",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Васильковое мини-платье",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221240029443,
    "title": "Blush Sparkle Maxi Dress",
    "slug": "blush-sparkle-maxi-dress",
    "price": 29000.0,
    "priceFormatted": "29 000 ₽",
    "image": "images/products/9221240029443.jpg",
    "handle": "blush-sparkle-maxi-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "maxi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Розовое макси-платье с кристаллами",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221148442883,
    "title": "Bordo Velour Rose Mini Dress",
    "slug": "bordo-velour-rose-mini-dress",
    "price": 27200.0,
    "priceFormatted": "27 200 ₽",
    "image": "images/products/9221148442883.jpg",
    "handle": "bordo-velour-rose-mini-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Бордовое мини-платье бархатная роза",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "red",
    "colorRu": "Красный"
  },
  {
    "id": 9220954423555,
    "title": "Camellia Mini Dress",
    "slug": "camellia-mini-dress",
    "price": 24200.0,
    "priceFormatted": "24 200 ₽",
    "image": "images/products/9220954423555.jpg",
    "handle": "camellia-mini-dress",
    "description": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "floral",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Камелия мини-платье",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221170462979,
    "title": "Caramel Glam Maxi Dress",
    "slug": "caramel-glam-maxi-dress",
    "price": 27200.0,
    "priceFormatted": "27 200 ₽",
    "image": "images/products/9221170462979.jpg",
    "handle": "caramel-glam-maxi-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "maxi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Карамельное макси-платье Glam",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221108400387,
    "title": "Corset Red Rose Mini Dress",
    "slug": "corset-red-rose-mini-dress",
    "price": 35500.0,
    "priceFormatted": "35 500 ₽",
    "image": "images/products/9221108400387.jpg",
    "handle": "corset-red-rose-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Корсет с красной розой мини-платье",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "red",
    "colorRu": "Красный"
  },
  {
    "id": 9221112889603,
    "title": "Corset White Rose Mini Dress",
    "slug": "corset-white-rose-mini-dress",
    "price": 35500.0,
    "priceFormatted": "35 500 ₽",
    "image": "images/products/9221112889603.jpg",
    "handle": "corset-white-rose-mini-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Корсет с белой розой мини-платье",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "white",
    "colorRu": "Белый"
  },
  {
    "id": 9221082775811,
    "title": "Forget-me-not Set Dress",
    "slug": "forget-me-not-set-dress",
    "price": 30000.0,
    "priceFormatted": "30 000 ₽",
    "image": "images/products/9221082775811.jpg",
    "handle": "forget-me-not-set-dress",
    "description": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "floral",
      "lace",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Незабудка платье комплект",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221186289923,
    "title": "Gold Fringe Midi Dress",
    "slug": "gold-fringe-midi-dress",
    "price": 27000.0,
    "priceFormatted": "27 000 ₽",
    "image": "images/products/9221186289923.jpg",
    "handle": "gold-fringe-midi-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "midi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Золотое миди-платье с бахромой",
    "category": "midi",
    "categoryRu": "Миди",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221198020867,
    "title": "Indigo Fringe Midi Dress",
    "slug": "indigo-fringe-midi-dress",
    "price": 27000.0,
    "priceFormatted": "27 000 ₽",
    "image": "images/products/9221198020867.jpg",
    "handle": "indigo-fringe-midi-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "midi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Индиго миди-платье с бахромой",
    "category": "midi",
    "categoryRu": "Миди",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221598019843,
    "title": "Ivory Tweed Mini Dress",
    "slug": "ivory-tweed-mini-dress",
    "price": 32500.0,
    "priceFormatted": "32 500 ₽",
    "image": "images/products/9221598019843.jpg",
    "handle": "ivory-tweed-mini-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Айвори мини-платье твидовое",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "light",
    "colorRu": "Светлый"
  },
  {
    "id": 9221495292163,
    "title": "Lavender Feather Jacket",
    "slug": "lavender-feather-jacket",
    "price": 41000.0,
    "priceFormatted": "41 000 ₽",
    "image": "images/products/9221495292163.jpg",
    "handle": "lavender-feather-jacket",
    "description": "Элегантное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feather jacket",
      "feminine"
    ],
    "available": true,
    "descriptionRu": "Элегантное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "UNO RÓBE жакет с перьями",
    "category": "outer",
    "categoryRu": "Жакеты",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221164892419,
    "title": "Maroon Cristal Maxi Dress",
    "slug": "maroon-cristal-maxi-dress",
    "price": 32900.0,
    "priceFormatted": "32 900 ₽",
    "image": "images/products/9221164892419.jpg",
    "handle": "maroon-cristal-maxi-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "maxi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Бордовое макси-платье с кристаллами",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "red",
    "colorRu": "Красный"
  },
  {
    "id": 9221499420931,
    "title": "Mint Feather Jacket",
    "slug": "mint-feather-jacket",
    "price": 41000.0,
    "priceFormatted": "41 000 ₽",
    "image": "images/products/9221499420931.jpg",
    "handle": "mint-feather-jacket",
    "description": "Элегантное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feather jacket",
      "feminine"
    ],
    "available": true,
    "descriptionRu": "Элегантное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Мятное жакет с перьями",
    "category": "outer",
    "categoryRu": "Жакеты",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221202346243,
    "title": "Olive Fringe Midi Dress",
    "slug": "olive-fringe-midi-dress",
    "price": 27000.0,
    "priceFormatted": "27 000 ₽",
    "image": "images/products/9221202346243.jpg",
    "handle": "olive-fringe-midi-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "midi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Оливковое миди-платье с бахромой",
    "category": "midi",
    "categoryRu": "Миди",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221077664003,
    "title": "Powder Flying Blouse",
    "slug": "powder-flying-blouse",
    "price": 21200.0,
    "priceFormatted": "21 200 ₽",
    "image": "images/products/9221077664003.jpg",
    "handle": "powder-flying-blouse",
    "description": "Элегантное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "blouse",
      "feminine",
      "lace"
    ],
    "available": true,
    "descriptionRu": "Элегантное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Пудровое блуза Flying",
    "category": "outer",
    "categoryRu": "Блузы",
    "color": "light",
    "colorRu": "Светлый"
  },
  {
    "id": 9221073666307,
    "title": "Powder Flying Maxi Dress",
    "slug": "powder-flying-maxi-dress",
    "price": 33000.0,
    "priceFormatted": "33 000 ₽",
    "image": "images/products/9221073666307.jpg",
    "handle": "powder-flying-maxi-dress",
    "description": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "lace",
      "maxi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Пудровое макси-платье Flying",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "light",
    "colorRu": "Светлый"
  },
  {
    "id": 9220958224643,
    "title": "Powder Maxi Dress",
    "slug": "powder-maxi-dress",
    "price": 31000.0,
    "priceFormatted": "31 000 ₽",
    "image": "images/products/9220958224643.jpg",
    "handle": "powder-maxi-dress",
    "description": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "lace",
      "maxi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Пудровое макси-платье",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "light",
    "colorRu": "Светлый"
  },
  {
    "id": 9221008982275,
    "title": "Red Azalea Mini Dress",
    "slug": "red-azalea-mini-dress",
    "price": 28500.0,
    "priceFormatted": "28 500 ₽",
    "image": "images/products/9221008982275.jpg",
    "handle": "red-azalea-mini-dress",
    "description": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "mini dress",
      "romantic"
    ],
    "available": true,
    "descriptionRu": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Красное мини-платье Azalea",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "red",
    "colorRu": "Красный"
  },
  {
    "id": 9221122621699,
    "title": "Red Flounce Mini Dress",
    "slug": "red-flounce-mini-dress",
    "price": 22800.0,
    "priceFormatted": "22 800 ₽",
    "image": "images/products/9221122621699.jpg",
    "handle": "red-flounce-mini-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Красное мини-платье с воланами",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "red",
    "colorRu": "Красный"
  },
  {
    "id": 9221156962563,
    "title": "V-neck Black Velour Maxi Dress",
    "slug": "v-neck-black-velour-maxi-dress",
    "price": 29500.0,
    "priceFormatted": "29 500 ₽",
    "image": "images/products/9221156962563.jpg",
    "handle": "v-neck-black-velour-maxi-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "maxi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Чёрное бархатное с V-вырезом макси-платье",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "black",
    "colorRu": "Чёрный"
  },
  {
    "id": 9221069013251,
    "title": "Violet Iris Maxi Dress",
    "slug": "violet-iris-maxi-dress",
    "price": 35000.0,
    "priceFormatted": "35 000 ₽",
    "image": "images/products/9221069013251.jpg",
    "handle": "violet-iris-maxi-dress",
    "description": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "floral",
      "maxi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Фиолетовое макси-платье Iris",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "other",
    "colorRu": "Другой"
  },
  {
    "id": 9221117870339,
    "title": "White Flounce Mini Dress",
    "slug": "white-flounce-mini-dress",
    "price": 22800.0,
    "priceFormatted": "22 800 ₽",
    "image": "images/products/9221117870339.jpg",
    "handle": "white-flounce-mini-dress",
    "description": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "cocktail dress",
      "feminine",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное коктейльное платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Белое мини-платье с воланами",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "white",
    "colorRu": "Белый"
  },
  {
    "id": 9221093490947,
    "title": "White Lace Mini Dress",
    "slug": "white-lace-mini-dress",
    "price": 25500.0,
    "priceFormatted": "25 500 ₽",
    "image": "images/products/9221093490947.jpg",
    "handle": "white-lace-mini-dress",
    "description": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "lace",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Белое мини-платье кружевное",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "white",
    "colorRu": "Белый"
  },
  {
    "id": 9220885741827,
    "title": "White Magnolia Mini Dress",
    "slug": "white-magnolia-mini-dress",
    "price": 36800.0,
    "priceFormatted": "36 800 ₽",
    "image": "images/products/9220885741827.jpg",
    "handle": "white-magnolia-mini-dress",
    "description": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "floral",
      "lace",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Белое мини-платье Magnolia",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "white",
    "colorRu": "Белый"
  },
  {
    "id": 9221050663171,
    "title": "White O'Hara Mini Dress",
    "slug": "white-o-hara-mini-dress",
    "price": 23500.0,
    "priceFormatted": "23 500 ₽",
    "image": "images/products/9221050663171.jpg",
    "handle": "white-ohara-mini-dress-1",
    "description": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "floral",
      "mini dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное мини-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Белое мини-платье O'Hara",
    "category": "mini",
    "categoryRu": "Мини",
    "color": "white",
    "colorRu": "Белый"
  },
  {
    "id": 9221060526339,
    "title": "Yellow Iris Maxi Dress",
    "slug": "yellow-iris-maxi-dress",
    "price": 35000.0,
    "priceFormatted": "35 000 ₽",
    "image": "images/products/9221060526339.jpg",
    "handle": "yellow-iris-maxi-dress",
    "description": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "tags": [
      "feminine",
      "floral",
      "maxi dress"
    ],
    "available": true,
    "descriptionRu": "Элегантное макси-платье из коллекции UNO RÓBE. Акцент на посадке, фактуре и выразительных деталях. Идеально для особого случая или вечернего образа.",
    "titleRu": "Жёлтое макси-платье Iris",
    "category": "maxi",
    "categoryRu": "Макси",
    "color": "other",
    "colorRu": "Другой"
  }
];
window.PRODUCTS_STATIC = PRODUCTS;
